spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/q1226085152/hello-spring-cloud
          username:
          password:
          search-paths: hello-spring-cloud-config/src/main/resources/respo

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/