spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8766

feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
